- a basic inclusion of the 3d generated tombstone
aocole/epitaph pull request #2
Opened 2017-03-03 19:28 UTC by billmerrill

Render a 3d tombstone based on Name and Text on the share page.

Important changes that might need review
-application view js include location (in header rather than at bottom of body
-use of alphetics to set order of js includes ("zjs" directory) because I wasn't sure how to get rails to do it for me
-lack of compartmentalization for "threedee" scripts, I don't know how to get rails to put the resources on one page only.

-Future work: customization of the download controls and potentially integration with shapeways.

comments appreciated!

2017-03-03 22:41 UTC, aocole commented
Here's how I would wrangle the asset pipeline to address your bullet points:
* Create an `index.js` in your threedee/ folder which loads the other files in the order you want, using the `//= require filename` syntax. [About index.js](http://guides.rubyonrails.org/asset_pipeline.html#using-index-files).
* Create a new "manifest" js file alongside application.js, called `threedee.js` containing `//= require threedee`. [About manifests](http://guides.rubyonrails.org/asset_pipeline.html#manifest-files-and-directives)
* Remove `require_tree .` from application.js <-- this is what is currently causing your files to load alphabetically
* Revert your changes to `config/initializers/assets.rb` and replace with `Rails.application.config.assets.precompile += %w( threedee.js )` to precompile the manifest you created above.
* On only the page you want to use the threedee libs, add `<%= javascript_include_tag "threedee" %>`. If it has to be in the <head> you could use a flag variable like `@load_threedee_js` and add an `if` to the include in the layout.

2017-03-03 22:42 UTC, aocole requested changes
Overall this looks awesome and I am super psyched that it worked out so well. Definitely want to get this integrated.

Here's how I would wrangle the asset pipeline to address your bullet points:
* Create an `index.js` in your threedee/ folder which loads the other files in the order you want, using the `//= require filename` syntax. [About index.js](http://guides.rubyonrails.org/asset_pipeline.html#using-index-files).
* Create a new "manifest" js file alongside application.js, called `threedee.js` containing `//= require threedee`. [About manifests](http://guides.rubyonrails.org/asset_pipeline.html#manifest-files-and-directives)
* Remove `require_tree .` from application.js <-- this is what is currently causing your files to load alphabetically
* Revert your changes to `config/initializers/assets.rb` and replace with `Rails.application.config.assets.precompile += %w( threedee.js )` to precompile the manifest you created above.
* On only the page you want to use the threedee libs, add `<%= javascript_include_tag "threedee" %>`. If it has to be in the \<head\> you could use a flag variable like `@load_threedee_js` and add an `if` to the include in the layout.

2017-03-03 22:42 UTC, aocole commented on app/views/epitaphs/share.html.erb
> +    SOONRIP['ep'] = { name: "<%= @epitaph.name %>",
These should be javascript-escaped to prevent problems with people including quotes or newlines in their text. e.g.:
`<%= j(@epitaph.name) %>`

2017-03-03 23:02 UTC, aocole commented on app/views/epitaphs/share.html.erb
> +    <div oncontextmenu="return false;" id="viewerContext" style="width: 50 vw; height: 50vh"></div>
Chrome complains that `50 vw` is invalid. Maybe should be `50vw`? Honestly I have never seen vw as a unit in CSS before and I have no idea what this is. Googling now...

2017-03-03 23:04 UTC, aocole commented on app/views/epitaphs/share.html.erb
> +    <div oncontextmenu="return false;" id="viewerContext" style="width: 50 vw; height: 50vh"></div>
handy!

2017-03-03 23:13 UTC, billmerrill commented on app/views/epitaphs/share.html.erb
> +    <div oncontextmenu="return false;" id="viewerContext" style="width: 50 vw; height: 50vh"></div>
it's very handy css3.  i don't want it in the div markup anyways, but 1 plumbing problem at a time.

2017-03-05 22:21 UTC, aocole approved these changes

2017-03-05 22:22 UTC, billmerrill commented
FUN

2017-03-05 22:22 UTC, merged